version: "3"
volumes:
  postgresdb:
  devcon:

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: deploymentdb
    ports:
      - "5432:5432"
    volumes:
      - postgresdb:/var/lib/postgresql/data
    restart: always


  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 3002:80
    environment:
      PGADMIN_DEFAULT_EMAIL: tum@seba.lab
      PGADMIN_DEFAULT_PASSWORD: tum


  arduino:
    image: solarbotics/arduino-cli-arduino-avr:1.8.4-0.20.0-node16.13
    command: >
      bash -c "arduino-cli config init --overwrite &&
               arduino-cli config add board_manager.additional_urls https://github.com/stm32duino/BoardManagerFiles/raw/main/package_stmicroelectronics_index.json &&
               arduino-cli core update-index &&
               arduino-cli core install arduino:sam@1.6.12 &&
               arduino-cli core install STMicroelectronics:stm32 &&
               arduino-cli daemon --port 50051 --daemonize --verbose"
    network_mode: host
    privileged: true
    volumes:
      - devcon:/usr/src/app/artifacts
    restart: always

  devcon:
    profiles:
      - "production"
    build:
      context: .
      dockerfile: Dockerfile.devcon
    env_file:
      - .docker/device-connector/env
    network_mode: host
    privileged: true
    volumes:
      - devcon:/usr/src/app/artifacts
    restart: always
