name: Bug report
description: Create a bug report to help us improve.
title: '[Bug]: '
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: >
        Thank you for taking the time to fill out a bug report. Remember to fill
        out all fields including the title above.

        An issue that is not properly filled out will be closed.
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: >
        Description of the problem or issue here.

        Include entries of affected devices / vendors / packages etc.

        If this is a crash, post the crashlog (upload to
        https://gist.github.com/) and include the link here.
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behaviour
      description: |
        Tell us what should happen instead.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source
      description: >
        If you have a source that proves how it is supposed to work, please add
        that to make it easier for devs to fix the issue.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        What does someone else need to do to encounter the same issue?
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: >
        Do you have any extra notes that can help solve the issue that does not
        fit any other field?
      placeholder: |
        None
    validations:
      required: false
  - type: textarea
    id: commit
    attributes:
      label: Code rev. hash/commit
      description: |
        Add the commit hash of the version you have running.
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Node version
      description: |
        NodeJS Version, e.g. 16.13.0
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: |
        Operating System, e.g. Ubuntu 20.04, Windows 10 x64, etc
    validations:
      required: true
  - type: textarea
    id: custom
    attributes:
      label: Custom changes
      description: >
        List which custom changes you have applied, e.g. Support for different
        devices / fqbns, etc.
      placeholder: |
        None
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thank you for your contribution.
