on: [push, pull_request]
name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "yarn"

      - name: Install
        run: yarn install --ignore-scripts

      - name: Check
        run: yarn run typecheck

      - name: Lint
        run: yarn run lint

      - name: Test
        run: yarn run test
