name: docker-build
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Build Demo
        run: docker-compose build --no-cache demo
